name: SantaEngine
options:
  bundleIdPrefix: com.muntazirfx
targets:
  SantaEngine:
    type: application
    platform: iOS
    deploymentTarget: "14.0"
    sources:
      - ios
      - path: src
        excludes:
          - "main.cpp"
    settings:
      INFOPLIST_FILE: ios/Info.plist
      CODE_SIGNING_ALLOWED: NO
      CODE_SIGNING_REQUIRED: NO
      HEADER_SEARCH_PATHS:
        - $(SRCROOT)/src
      CLANG_CXX_LANGUAGE_STANDARD: "c++17"
      CLANG_CXX_LIBRARY: "libc++"
    dependencies:
      - sdk: UIKit.framework
